apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ecommerce-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.ecommerceUi.replicas }}
  strategy:
    blueGreen:
      activeService: ecommerce-ui-active
      previewService: ecommerce-ui-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: ecommerce-ui
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: ecommerce-ui
        version: v1
    spec:
      containers:
      - name: ecommerce-ui
        image: {{ .Values.ecommerceUi.image }}:{{ .Values.ecommerceUi.tag1 }}
        ports:
        - containerPort: {{ .Values.ecommerceUi.containerPort }}
        env:
    {{- toYaml .Values.ecommerceUi.env | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui-active
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.ecommerceUi.servicePort }}
    name: http
  selector:
    app: ecommerce-ui
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui-preview
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.ecommerceUi.servicePort }}
    name: http
  selector:
    app: ecommerce-ui