apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: order-management
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.orderManagement.replicas }}
  strategy:
    blueGreen:
      activeService: order-management-active
      previewService: order-management-preview
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: order-management
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: order-management
        version: v1
    spec:
      containers:
      - name: order-management
        image: {{ .Values.orderManagement.image }}:{{ .Values.orderManagement.tag2 }}
        ports:
        - containerPort: {{ .Values.orderManagement.containerPort}}
        env:
    {{- toYaml .Values.orderManagement.env | nindent 8 }}

---
apiVersion: v1
kind: Service
metadata:
  name: order-management-active
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.orderManagement.servicePort}}
    name: http
  selector:
    app: order-management
---

apiVersion: v1
kind: Service
metadata:
  name: order-management-preview
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.orderManagement.servicePort}}
    name: http
  selector:
    app: order-management

