apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: shipping-and-handling
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.shippingAndHandling.replicas }}
  strategy:
    blueGreen:
      activeService: shipping-and-handling-active
      previewService: shipping-and-handling-passive
      autoPromotionEnabled: false
  selector:
    matchLabels:
      app: shipping-and-handling
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: shipping-and-handling
        version: v1
    spec:
      containers:
      - name: shipping-and-handling
        image: {{ .Values.shippingAndHandling.image }}:{{ .Values.shippingAndHandling.tag6 }}
        ports:
        - containerPort: {{ .Values.shippingAndHandling.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-and-handling-active
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.shippingAndHandling.servicePort }}
    name: http
  selector:
    app: shipping-and-handling
---

apiVersion: v1
kind: Service
metadata:
  name: shipping-and-handling-passive
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.shippingAndHandling.servicePort }}
    name: http
  selector:
    app: shipping-and-handling