
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecommerce-gateway-routes
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ .Values.VirtualService.hosts }}"
  gateways:
  - ecommerce-gateway
  http:
  - name: primary
    match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Values.VirtualService.destinationHostActive }}
        port:
          number: {{ .Values.VirtualService.port }}
